// This file is auto-generated by @hey-api/openapi-ts — do not edit by hand.
// Regenerate with: pnpm generate (from repo root) after schema changes.

import { createClient, createConfig, type Client } from "@hey-api/client-fetch";
import type { HealthResponse } from "./types.gen";

// The client is created with an empty baseUrl; the consuming application must
// call `configureClient` before making requests, or pass options per-call.
export const client: Client = createClient(createConfig());

/**
 * Override the base URL for all requests.
 * Call this once at app startup: `configureClient({ baseUrl: ... })`
 */
export const configureClient = (config: { baseUrl: string }) => {
  client.setConfig({ baseUrl: config.baseUrl });
};

/** GET /health — returns `{"status":"ok"}` when the backend is running. */
export const getHealth = () =>
  client.get<HealthResponse, unknown>({ url: "/health" });
