// This file is auto-generated by @hey-api/openapi-ts — do not edit by hand.
// Regenerate with: pnpm generate (from repo root) after schema changes.

export type HealthResponse = {
  status: string;
};
